{% set name = "ssh-utilities" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ssh_utilities-{{ version }}.tar.gz
  sha256: b93d28e968976102d0a1b4363a0e6e484fde28610026f386e4ffb484fc345c00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - paramiko >=2.7.1
    - typing-extensions >=3.7.4.2
    - colorama >=0.4.3
    - tqdm >=4.47.0

test:
  imports:
    - ssh_utilities
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marian-code/ssh-utilities
  summary: paramiko convenience wrapper
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
